Add EvenProcessorOptions and rename prop DeleteCheckpointStore
RaaLabs/Edge pull request #28
Opened 2021-07-02 09:30 UTC by srudaa

## Summary

### Added

- EventProcessorOptions as prop in IEventHubConnection

### Changed

- DeleteCheckpointStore to DeleteCheckpointStoreAtStartup

2021-07-02 10:00 UTC, thotokraa requested changes

2021-07-02 10:00 UTC, thotokraa commented on Edge.Modules.EventHub/IEventHubConnection.cs
> +        public EventProcessorOptions Options { get; set;}
I think the name `Options` is a bit too ambiguous, as it pertains only to reading from EventHubs, not writing to them. How about `ReaderOptions`?

2021-07-02 10:28 UTC, srudaa commented on Edge.Modules.EventHub/IEventHubConnection.cs
> +        public EventProcessorOptions Options { get; set;}
Good idea

2021-07-05 10:19 UTC, thotokraa approved these changes

2021-07-05 10:49 UTC, merged